ezplatform:
    system:
        site_group:
            pagelayout: "@ezdesign/pagelayout.html.twig"
            field_templates:
                - { template: '@ezdesign/fields/content_fields.html.twig', priority: 20 }
            content_view:
                full:
                    home:
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home

                    inspiration_list:
                        controller: "App\\Controller\\PaginationQueryController:contentQueryAction"
                        template: "@ezdesign/full/inspiration_list.html.twig"
                        match:
                            Identifier\ContentType: inspiration_list
                        params:
                            limit: 10
                            query:
                                query_type: "App:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                    included_content_type_identifier: 'inspiration'
                                assign_results_to: inspirations
                    inspiration:
                        template: "@ezdesign/full/inspiration.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    store_list:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/store_list.html.twig"
                        match:
                            Identifier\ContentType: store_list
                        params:
                            query:
                                query_type: "App:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                    included_content_type_identifier: 'store'
                                assign_results_to: stores

                    store:
                        template: "@ezdesign/full/store.html.twig"
                        match:
                            Identifier\ContentType: store
                card:
                    inspiration:
                        template: "@ezdesign/card/inspiration.html.twig"
                        match:
                            Identifier\ContentType: inspiration

                    store:
                        template: "@ezdesign/card/store.html.twig"
                        match:
                            Identifier\ContentType: store
        professionals:
            content_view:
                full:
                    home:
                        controller: "ez_query:contentQueryAction"
                        template: "@ezdesign/full/home.html.twig"
                        match:
                            Identifier\ContentType: home
                        params:
                            query:
                                query_type: "App:Children"
                                parameters:
                                    parent_location_id: "@=location.id"
                                assign_results_to: professionals
