# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: front

# The type of the application to build.
type: php:5.6
build:
    flavor: symfony

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: "mysql:mysql"

# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: "/web"
    # The front-controller script to send non-static requests to.
    passthru: "/app.php"
    # The number of seconds whitelisted (static) content should be cache
    expires: 600
    # Static content whitelist, everything else goes to passthru
    whitelist:
      # root files
      - /robots\.txt$
      - /favicon\.ico$
      # binary files that can be served
      - /var/([^/]+/)?storage/images(-versioned)?/(.*)
      # assets
      - /bundles/(.*)
      - /css/(.*)\.css$
      - /js/(.*)\.js$
      # fonts
      - /font/(.*)\.ttf$
      - /font/(.*)\.woff$
      - /font/(.*)\.otf$
      - /font/(.*)\.eot$
      - /font/(.*)\.svg$

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/app/cache": "shared:files/cache"
    "/app/logs": "shared:files/logs"
    "/web/var": "shared:files/files"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      rm web/app_dev.php
      app/console --env=prod assetic:dump
    deploy: |
      app/console --env=prod cache:clear

# The configuration of scheduled execution.
# see http://symfony.com/doc/current/components/console/introduction.html
#crons:
#    symfony:
#        spec: "*/20 * * * *"
#        cmd: "php cron.php example:test"

runtime:
    extensions:
        - xsl
        - imagick
