sudo: required
dist: trusty
language: generic

services:
  - docker

env:
  global:
    - COMPOSE_FILE="doc/docker-compose/base-dev.yml:doc/docker-compose/selenium.yml"
    - INSTALL_EZ_INSTALL_TYPE=demo
  # list of behat arguments to test
  matrix:
    - ARGS="--profile=rest --suite=fullJson" COMPOSE_FILE="doc/docker-compose/base-prod.yml:doc/docker-compose/selenium.yml" REMOTE_IMAGE="ezsystems/ezplatform-demo" APP_PROD_IMAGE="ezplatform-demo"
    - ARGS="--profile=rest --suite=fullXml" SYMFONY_ENV=behat SYMFONY_DEBUG=1
    - ARGS="--profile=core" SYMFONY_ENV=behat SYMFONY_DEBUG=1

# test only master (+ Pull requests)
branches:
  only:
    - master
    - /^\d.\d$/
    - /^v\d.\d.\d$/

# Update Docker and Docker Compose
before_install: ./bin/.travis/trusty/update_docker.sh

before_script:
  # Internal auth token dedicated to testing with travis+composer on ezsystems repos, not for reuse!
  - echo "{\"github-oauth\":{\"github.com\":\"d0285ed5c8644f30547572ead2ed897431c1fc09\"}}" > auth.json
  # In case of dev mode we'll need to install composer packages first
  - docker-compose -f doc/docker-compose/install.yml up --abort-on-container-exit
  # Run (start containers and execute install command)
  - docker-compose up -d
  #- docker ps
  #- docker-compose logs

# execute behat as the script command, need to use sh to get right exit code (docker/compose/issues/3379)
# using behat.yml which is a copy of behat.yml.dist with hostnames update by docker-compose.behat.yml
script: docker-compose exec --user www-data app sh -c "php /scripts/wait_for_db.php; php bin/behat -vv $ARGS --tags=~@broken"

# Push prod image to docker hub on sucess (on tags)
after_success: if [ "$REMOTE_IMAGE" != "" ] && [ "$TRAVIS_TAG" != "" ]; then bin/.ci/docker_hub_push.sh ${APP_PROD_IMAGE} ${REMOTE_IMAGE}; fi

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
