language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

# test only master (+ Pull requests)
branches:
  only:
    - master
    # Stable branches
    - /^\d.\d+$/
    # Stable tags (for after_success deployment)
    - /^v\d.\d+.\d+(\+demo\.v\d+)?$/

before_script:
  - phpenv config-rm xdebug.ini
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - travis_retry composer selfupdate
  - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - php app/console doctrine:database:create
  - php app/console ezplatform:install demo

# disable mail notifications
notifications:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30
