imports:
    - { resource: image_variations.yml }
    - { resource: views.yml }

ezpublish:
    # HttpCache settings, By default 'local' (Symfony HttpCache Proxy), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: '%search_engine%'
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list:
            - site
            - admin
            - fr
            - de
            - no
        groups:
            site_group:
                - site
                - fr
                - de
                - no
            # WARNING: Do not remove or rename this group.
            # It's used to distinguish common siteaccesses from admin ones.
            # In case of multisite with multiple admin panels, remember to add any additional admin siteaccess to this group.
            admin_group: [admin]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            # Cache pool service, needs to be different per repository (database) on multi repository install.
            cache_service_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            content:
                # As we by default enable EzSystemsPlatformHttpCacheBundle which is designed to expire all affected cache
                # on changes, and as error / redirects now have separate ttl, we easier allow ttl to be greatly increased
                default_ttl: '%httpcache_default_ttl%'
            # HttpCache purge server(s) setting, eg Varnish, for when ezpublish.http_cache.purge_type is set to 'http'.
            http_cache:
                purge_servers: ['%purge_server%']
            design: main
        # WARNING: Do not remove or rename this group.
        admin_group:
            cache_service_name: '%cache_pool%'
            var_dir: var/site
            languages:
                - eng-GB
                - fre-FR
                - ger-DE
                - nor-NO
            content:
                default_ttl: '%httpcache_default_ttl%'
            http_cache:
                purge_servers: ['%purge_server%']
            design: admin
        site:
            languages:
                - eng-GB
                - fre-FR
                - ger-DE
                - nor-NO
        fr:
            languages:
                - fre-FR
                - eng-GB
        de:
            languages:
                - ger-DE
                - eng-GB
        no:
            languages:
                - nor-NO
                - eng-GB

ezdesign:
    design_list:
        main: [tastefulplanet]
        admin: [admin, tastefulplanet]

assetic:
    assets:
        css_default:
            inputs:
                - 'assets/css/tastefulplanet.css'
                - 'assets/css/header.css'
                - 'assets/css/footer.css'
                - 'assets/css/home.css'
                - 'assets/css/article.css'
                - 'assets/css/folder.css'
                - 'assets/css/place.css'
                - 'assets/css/place_list.css'
                - 'assets/css/blog.css'
                - 'assets/css/blog_post.css'
                - 'assets/css/subscribe.css'
                - 'assets/css/tags.css'
