imports:
    - { resource: image_variations.yml }
    - { resource: views.yml }

ezpublish:
    # HttpCache settings, By default 'local' (Symfony HttpCache Proxy), by setting it to 'http' you can point it to Varnish
    http_cache:
        purge_type: '%purge_type%'

    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: '%search_engine%'
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list:
            - site
            - admin
            - fr
            - de
            - no
        groups:
            site_group:
                - site
                - fr
                - de
                - no
            # WARNING: Do not remove or rename this group.
            # It's used to distinguish common siteaccesses from admin ones.
            # In case of multisite with multiple admin panels, remember to add any additional admin siteaccess to this group.
            admin_group: [admin]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            # Cache pool service, needs to be different per repository (database) on multi repository install.
            cache_service_name: '%cache_pool%'
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this list may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            languages: [eng-GB]
            content:
              # As we by default enable EzSystemsPlatformHttpCacheBundle which is designed to expire all affected cache
              # on changes, and as error / redirects now have separate ttl, we easier allow ttl to be greatly increased
              default_ttl: '%httpcache_default_ttl%'
            # HttpCache purge server(s) setting, eg Varnish, for when ezpublish.http_cache.purge_type is set to 'http'.
            http_cache:
                purge_servers: ['%purge_server%']
            # Temporary hard coding session name during v2 development
            session:
                name: eZSESSID
            # ez-design-engine configuration
            design: main
        # WARNING: Do not remove or rename this group.
        admin_group:
            cache_service_name: '%cache_pool%'
            var_dir: var/site
            languages:
                - eng-GB
                - fre-FR
                - ger-DE
                - nor-NO
            content:
                default_ttl: '%httpcache_default_ttl%'
            http_cache:
                purge_servers: ['%purge_server%']
            session:
                name: eZSESSID
        site:
            languages:
                - eng-GB
                - fre-FR
                - ger-DE
                - nor-NO
        fr:
            languages:
                - fre-FR
                - eng-GB
        de:
            languages:
                - ger-DE
                - eng-GB
        no:
            languages:
                - nor-NO
                - eng-GB

ezdesign:
    design_list:
        main: [tastefulplanet]

assetic:
    assets:
        css_default:
            inputs:
                - 'assets/css/tastefulplanet.css'
                - 'assets/css/header.css'
                - 'assets/css/footer.css'
                - 'assets/css/article.css'
                - 'assets/css/folder.css'
                - 'assets/css/place.css'

nova_ezseo:
    system:
        default:
            #custom_fallback_service: ezstudiodemo.seo.fallback
            default_links:
                Index:
                    href: { location_id: 2 }
                    title: "Home"
#                Search:
#                    href: { route: "ezpublish_ezstudiodemo_search" }
#                    title: "Search"
#                "Shortcut icon":
#                    href: { asset: "/bundles/ezstudiodemo/images/favicon.ico" }
#                    type: "image/x-icon"
            default_metas:
                author: "eZ Systems"
                copyright: "eZ Systems"
                generator: "eZ Platform"
                MSSmartTagsPreventParsing: ~
            fieldtype_metas:
                title:
                    label: "Title"
                    default_pattern: "<title|short_title|name>"
                description:
                    label: "Description"
                    default_pattern: "<description|short_description|intro|title|name>"
                keywords:
                    label: "Keywords"
                    default_pattern: "<tags>"
                canonical:
                    label: "External Canonical URL"
                    default_pattern: ~
                    icon: "link"
                "og:title":
                    label: "Facebook - Title"
                    default_pattern: "<title|short_title|name>"
                    icon: "facebook-official"
                "og:description":
                    label: "Facebook - Description"
                    default_pattern: "<short_description|description|intro|title|name>"
                    icon: "facebook-official"
                "og:image":
                    label: "Facebook - Image"
                    default_pattern: "<image|picture>"
                    icon: "facebook-official"
                "twitter:title":
                    label: "Twitter - Title"
                    default_pattern: "<title|short_title|name>"
                    icon: "twitter-square"
                "twitter:description":
                    label: "Twitter - Description"
                    default_pattern: "<short_description|description|intro|title|name>"
                    icon: "twitter-square"
                "twitter:image":
                    label: "Twitter - Image"
                    default_pattern: "<image|picture>"
                    icon: "twitter-square"
