services:
    twig.extension.array:
        class: Twig_Extensions_Extension_Array
        tags:
            - { name: twig.extension }

    app.paginated_query_controller:
        class: AppBundle\Controller\PagerFantaQueryController
        arguments:
            - '@ezpublish.query_type_content_view_mapper'
            - '@ezpublish.api.service.search'

    app.installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\AppInstaller
        tags:
            - { name: ezplatform.installer, type: demo }

    app.query_type.latest_content:
        class: AppBundle\QueryType\LatestContentQueryType
        calls:
            - [setLanguages, [$languages$]]
        tags:
            - { name: ezpublish.query_type }

    app.criteria.menu:
        class: AppBundle\Criteria\Menu

    app.controller.menu:
        class: AppBundle\Controller\MenuController
        arguments:
            - '@templating'
            - '@ezpublish.api.service.search'
            - '@ezpublish.api.service.location'
            - '@ezpublish.config.resolver'
            - '@app.criteria.menu'
            - '%app.top_menu.location_id%'

    app.form.type.contact:
        class: AppBundle\Form\Type\ContactType
        tags:
            - { name: form.type, alias: app_contact }

    app.entity.message:
        class: AppBundle\Entity\Message

    app.form.contact.form:
        class: AppBundle\Form\Contact\Form
        arguments:
            - '@app.entity.message'
            - '@app.form.type.contact'
            - '@form.factory'

    app.controller.contactform:
        class: AppBundle\Controller\ContactFormController
        arguments:
            - '@app.form.type.contact'
            - '@app.form.contact.form'
            - '@app.mail.sender'
            - '@templating'
            - '@hautelook.router.template'
            - '%app.contact_form.sender_email%'
            - '%app.contact_form.recipient_email%'
            - '%app.contact_form.email_title%'

    app.mail.sender:
        class: AppBundle\Mail\Sender
        arguments:
            - '@mailer'
