"http://{default}/":
    type: upstream
    upstream: "front:http"
    cache:
        # As this does not support Vary, and purging, we can't use this as Sf Proxy drop in.
        # However it is possible to enable this for anonymous traffic when backend sends expiry headers.
        enabled: false

"http://www.{default}/":
    type: redirect
    to: "http://{default}/"
