services:
    app.form.type.contact:
        class: AppBundle\Form\Type\ContactType
        tags:
            - { name: form.type, alias: app_contact }

    app.entity.message:
        class: AppBundle\Entity\Message

    app.form.contact.form:
        class: AppBundle\Form\Contact\Form
        arguments:
            - '@app.entity.message'
            - '@app.form.type.contact'
            - '@form.factory'
